import { OnInit } from '@angular/core';
import { TerraTreeComponent, TerraOverlayComponent } from '@plentymarkets/terra-components/index';
import { TaxonomyService } from "./service/taxonomy.service";
import { EtsyComponent } from "../etsy-app.component";
import { LocaleService } from "angular2localization/angular2localization";
import { LocalizationService } from "angular2localization/angular2localization";
import { Locale } from "angular2localization/angular2localization";
export declare class TaxonomiesComponent extends Locale implements OnInit {
    private taxonomyService;
    private etsyComponent;
    private isLoading;
    private taxonomiesList;
    private taxonomiesNameList;
    private correlations;
    private categories;
    private pagingData;
    private rowInOverlay;
    private correlationsLoaded;
    private updateTaxonomyPrimaryButtonOverlay;
    viewTaxonomiesOverlay: TerraOverlayComponent;
    tree: TerraTreeComponent;
    constructor(taxonomyService: TaxonomyService, etsyComponent: EtsyComponent, locale: LocaleService, localization: LocalizationService);
    ngOnInit(): void;
    private doPaging(pagerData);
    private getTaxonomies();
    private getCorrelations();
    private getData(perPage, currentPage);
    private getTaxonomyName(taxonomyId);
    private openTaxonomiesOverlay(row);
    private updateTaxonomy();
    private buildTaxonomiesTree(taxonomies);
    private getLeaf(item);
    private saveCorrelations();
    private updateOrAddCorrelation(categoryData);
    private calculatePagingData(response, perPage, currentPage);
    private reload();
}
