import { OnInit } from '@angular/core';
import { TerraOverlayComponent, TerraTreeComponent } from '@plentymarkets/terra-components/index';
import { EtsyComponent } from "../etsy-app.component";
import { Locale } from "angular2localization/angular2localization";
import { LocaleService } from "angular2localization/angular2localization";
import { LocalizationService } from "angular2localization/angular2localization";
import { PropertyService } from "./service/property.service";
export declare class PropertiesComponent extends Locale implements OnInit {
    private propertyService;
    private etsyComponent;
    private isLoading;
    private correlations;
    private marketPropertiesNameList;
    private propertiesNameList;
    private propertiesRowInOverlay;
    private marketPropertiesSettingsRowInOverlay;
    private propertiesTreeList;
    private marketPropertiesSettingsTreeList;
    private updatePropertyPrimaryButtonOverlay;
    private updateMarketPropertySettingsPrimaryButtonOverlay;
    viewPropertiesOverlay: TerraOverlayComponent;
    viewMarketPropertiesSettingsOverlay: TerraOverlayComponent;
    propertyTree: TerraTreeComponent;
    marketPropertySettingsTree: TerraTreeComponent;
    constructor(propertyService: PropertyService, etsyComponent: EtsyComponent, locale: LocaleService, localization: LocalizationService);
    ngOnInit(): void;
    private getProperties();
    private getMarketProperties();
    private getCorrelations();
    private getMarketPropertyName(marketPropertySettingsId);
    private buildMarketPropertiesSettingsTree(marketPropertiesSettings);
    private getPropertyName(propertyId);
    private buildPropertiesTree(propertiesSettings);
    private openPropertiesOverlay(row);
    private openMarketPropertiesSettingsOverlay(row);
    private getPropertyLeaf(item);
    private updateProperty();
    private updateMarketPropertySettings();
    private addCorrelation();
    private removeCorrelation(item);
    private saveCorrelations();
    private import();
}
